version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db-short-url
    expose:
        - 27017
    volumes:
        - ./mongodb:/data/db
  node_server:
    build: ./
    container_name: egg-short-url
    links:
        - mongodb:mongo
    expose:
        - 3000