version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db-short-url
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    expose:
      - 27017
    volumes:
      - ./mongodb:/data/db
  node_server:
    build: ./
    container_name: egg-short-url
    environment:
      - TZ=Asia/Shanghai
    links:
      - "mongodb:mongo"
    ports:
      - 7000:3000
    depends_on:
      - mongodb
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx-short-url
    ports:
      - 1180:80
      - 11443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/gjw/myDockerFiles/nginx/conf/https:/ssl/:rw
      - ./static:/usr/share/nginx/html