version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db-short-url
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    expose:
      - 27017
    volumes:
      - ./mongodb:/data/db
  node_server:
    build: ./
    container_name: egg-short-url
    links:
      - "mongodb:mongo"
    ports:
      - 7000:3000
    depends_on:
      - mongodb