version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db-short-url
    environment:
      - AUTH=yes
      - ADMIN_USER=admin
      - ADMIN_PASS=123456
    expose:
        - 27017
    volumes:
        - /home/leisc/short/mongodb:/data/db
  node_server:
    build: /home/leisc/short/egg
    container_name: egg-short-url
    links:
        - mongodb:mongo
    expose:
        - 3000